/**
 * Managed-region markup for files generated by `lambda init`. A generated
 * file is frontmatter followed by a marked block; content the user appends
 * after MARKER_END survives a re-run untouched, and a file that predates
 * `lambda init` (no markers) is left alone entirely rather than clobbered.
 */

export const MARKER_START =
  "<!-- RECURSIVEPRAXIS:MANAGED:START (generated by `lambda init` — edits between this line and the END marker are overwritten on re-run; add custom content after the END marker instead) -->";
export const MARKER_END = "<!-- RECURSIVEPRAXIS:MANAGED:END -->";

/**
 * The visible notice inside every managed region, as alternating literal and
 * code segments. One structured definition, because it is rendered twice by
 * different machinery — as a raw string here, and as mdast phrasing nodes in
 * the managed-block plugin — and backticks that survive one path but not the
 * other would be a silent divergence between the two.
 */
export const MANAGED_NOTICE_SEGMENTS = [
  { code: false, value: "Generated by " },
  { code: true, value: "lambda init" },
  { code: false, value: ". Do not hand-edit between the RECURSIVEPRAXIS:MANAGED markers — re-run " },
  { code: true, value: "lambda init" },
  { code: false, value: " to refresh." },
] as const;

const VISIBLE_HEADER = `> ${MANAGED_NOTICE_SEGMENTS.map((segment) =>
  segment.code ? `\`${segment.value}\`` : segment.value,
).join("")}`;

export function hasManagedMarkers(content: string): boolean {
  return content.includes(MARKER_START) && content.includes(MARKER_END);
}

/** Frontmatter + markers + body, with no trailing user content. Used both to create new files and as the replacement head when refreshing existing ones. */
export function renderManagedHead(frontmatter: string, body: string): string {
  return [frontmatter.trim(), "", MARKER_START, "", VISIBLE_HEADER, "", body.trim(), "", MARKER_END, ""].join("\n");
}

export interface MergeResult {
  readonly content: string;
  readonly changed: boolean;
}

/**
 * Replaces everything from the start of `existing` through its END marker
 * with `freshHead`, preserving any content that follows the END marker
 * verbatim. Callers must check `hasManagedMarkers(existing)` first.
 *
 * `freshHead` always ends in exactly one newline after MARKER_END (see
 * renderManagedHead). The slice below therefore starts one character past
 * that newline too, so an untouched file round-trips byte-for-byte instead
 * of gaining a duplicate blank line on every re-run.
 */
export function mergeManaged(existing: string, freshHead: string): MergeResult {
  const endIndex = existing.indexOf(MARKER_END);
  const afterMarker = endIndex + MARKER_END.length;
  const trailing = existing.startsWith("\n", afterMarker) ? existing.slice(afterMarker + 1) : existing.slice(afterMarker);
  const content = `${freshHead}${trailing}`;
  return { content, changed: content !== existing };
}

/**
 * Everything `mergeManaged` will overwrite: the start of the file through
 * MARKER_END. Undefined when the file is not ours.
 *
 * This is what the install manifest hashes, and the boundary has to be this
 * one rather than the marker-delimited block, because the frontmatter above
 * MARKER_START is ours too — `mergeManaged` replaces it. Hashing only between
 * the markers would let a hand-edited `description:` read as clean in
 * `lambda doctor` and then be silently overwritten by `lambda sync`.
 *
 * Content after MARKER_END is still excluded, which is the property that
 * matters in the other direction: a user appending a section is keeping a
 * promise we made them, not causing drift.
 */
export function ownedHead(content: string): string | undefined {
  if (!hasManagedMarkers(content)) return undefined;
  const end = content.indexOf(MARKER_END);
  return content.slice(0, end + MARKER_END.length);
}

/**
 * The marker-delimited block alone, excluding frontmatter. Used for describing
 * drift structurally — which section changed — not for detecting it.
 */
export function managedRegion(content: string): string | undefined {
  const start = content.indexOf(MARKER_START);
  if (start === -1) return undefined;
  const end = content.indexOf(MARKER_END, start);
  if (end === -1) return undefined;
  return content.slice(start, end + MARKER_END.length);
}

