/**
 * Managed-region markup for files generated by `lambda init`. A generated
 * file is frontmatter followed by a marked block; content the user appends
 * after MARKER_END survives a re-run untouched, and a file that predates
 * `lambda init` (no markers) is left alone entirely rather than clobbered.
 */

export const MARKER_START =
  "<!-- RECURSIVEPRAXIS:MANAGED:START (generated by `lambda init` — edits between this line and the END marker are overwritten on re-run; add custom content after the END marker instead) -->";
export const MARKER_END = "<!-- RECURSIVEPRAXIS:MANAGED:END -->";

const VISIBLE_HEADER =
  "> Generated by `lambda init`. Do not hand-edit between the RECURSIVEPRAXIS:MANAGED markers — re-run `lambda init` to refresh.";

export function hasManagedMarkers(content: string): boolean {
  return content.includes(MARKER_START) && content.includes(MARKER_END);
}

/** Frontmatter + markers + body, with no trailing user content. Used both to create new files and as the replacement head when refreshing existing ones. */
export function renderManagedHead(frontmatter: string, body: string): string {
  return [frontmatter.trim(), "", MARKER_START, "", VISIBLE_HEADER, "", body.trim(), "", MARKER_END, ""].join("\n");
}

export interface MergeResult {
  readonly content: string;
  readonly changed: boolean;
}

/**
 * Replaces everything from the start of `existing` through its END marker
 * with `freshHead`, preserving any content that follows the END marker
 * verbatim. Callers must check `hasManagedMarkers(existing)` first.
 *
 * `freshHead` always ends in exactly one newline after MARKER_END (see
 * renderManagedHead). The slice below therefore starts one character past
 * that newline too, so an untouched file round-trips byte-for-byte instead
 * of gaining a duplicate blank line on every re-run.
 */
export function mergeManaged(existing: string, freshHead: string): MergeResult {
  const endIndex = existing.indexOf(MARKER_END);
  const afterMarker = endIndex + MARKER_END.length;
  const trailing = existing.startsWith("\n", afterMarker) ? existing.slice(afterMarker + 1) : existing.slice(afterMarker);
  const content = `${freshHead}${trailing}`;
  return { content, changed: content !== existing };
}
